controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\Users;
use yii\web\NotFoundHttpException;

class SiteController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout','verivikasiakun'],
                'rules' => [
                    [
                        'actions' => ['logout','verivikasiakun'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
   /*         'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
           ],
    * 
    */
        ];
    }

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionIndex()
    {
          $model = new Users();

        if ($model->load(Yii::$app->request->post())) {
            
            if (($m = Users::findOne(['a_email'=>$model->a_email])) !== null) {
             throw new NotFoundHttpException('Email Sudah Dipakai Silahkan Login atau Daftar dengan email lain');
            }
            
            $model->a_kode=$model->generateSalt(); 
            $model->a_password=$model->hashPassword($model->a_password,$model->a_kode);
            $model->level_id = 5;
            if ($model->save()){
                $kode = substr($model->a_kode, 0, 6);
                if($this->sendkode($model->a_email, $kode)){
                    return $this->redirect(['users/view', 'id' => $model->id]);
                }
            }
        } else {
            return $this->render('index', [
                'model' => $model,
            ]);
        }
    }

    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    public function actionAbout()
    {
        return $this->render('about');
    }
    
    public function actionVerivikasiakun()
    {
       
        $iduser = Yii::$app->user->identity->id;
        $model= Users::findOne($iduser);
        $akode = substr($model->a_kode, 0, 6);
         if ($model->load(Yii::$app->request->post())) {
            if ($akode == $model->kodeverivikasi){
                $model->level_id = 4;
             
            if ($model->save()){
                return $this->redirect(['users/view', 'id' => $model->id]);
            }
            } 
         }
         
        return $this->render('verivikasiakun', [
            'model' => $model,
        ]);
    }
    
   public function sendkode($email,$kode){
                $message=Yii::$app->mailer->compose();
                $message->setFrom('mailer@coconut.or.id');
                $message->setTo($email);
                $message->setSubject('Kode Verivikasi COCONUT' );
                $message->setHtmlBody('Kode verivikasi akun anda adalah <h2>'.$kode.'</h2> Silahkan verivikasi di daftar.coconut.or.id'
                        . 'atau dengan mengkilk link berikut'); 
              if ($message->send()){
              return true;
              }
   }
      
   public function actionKirimkode()
    {
        $iduser = Yii::$app->user->identity->id;
        $model= Users::findOne($iduser);
        $akode = substr($model->a_kode, 0, 6);
        if($this->sendkode($model->a_email, $akode)) {
            Yii::$app->session->setFlash('kodesend');

            return $this->redirect(['verivikasiakun']);
        }else{
          Yii::$app->session->setFlash('kode gagal terkirim');

            return $this->redirect(['verivikasiakun']);
        }
    } 

}

views/site/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\captcha\Captcha;
/* @var $this yii\web\View */
/* @var $model app\models\Users */
/* @var $form yii\widgets\ActiveForm */
?>
<h3 class="alert alert-danger"><span class="fa fa-pencil text-info"></span> Ayo Belajar Bersama <small>Coconut</small></h3>
<div class="users-form">

    <?php $form = ActiveForm::begin([
        'id' => 'users-form',
        'options' => ['class' => 'form-horizontal'],
        'fieldConfig' => [
            'template' => "<div class=\"col-sm-12\">{input}{error}</div>\n",
        ],
    ]); ?>

    <?= $form->field($model, 'a_nama')->textInput(['maxlength' => true , 'placeholder'=>'Nama Lengkap'])?>

    <?= $form->field($model, 'a_email')->Input('email',['maxlength' => true , 'placeholder'=>'E-Mail'])?>
    
    <?= $form->field($model, 'a_no_tlp')->textInput(['maxlength' => true, 'placeholder'=>'Nomor Telepon'])?>

    <?= $form->field($model, 'a_password')->passwordInput(['maxlength' => true, 'placeholder'=>'Password Akun'])?>

    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
        'template' => "<div class=\"col-sm-6\">{image}</div><div class=\"col-sm-6\">{input}</div>\n"
    ]) ?>
  
        <?= Html::submitButton($model->isNewRecord ? 'Registrasi' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success btn-lg btn-block' : 'btn btn-primary']) ?>


    <?php ActiveForm::end(); ?>

</div>

views/site/_halo.php
<?php
use yii\helpers\Html;
use yii\helpers\HtmlPurifier;
use yii\helpers\Url;
$foto = Yii::$app->user->identity->a_foto;
?>
<h2>Halo ! <br /> <small><?=  Yii::$app->user->identity->a_nama ?></small></h2>
<center>
    <?php if($foto!=null){
        echo Html::img('@web/uploads/users/'.$foto,['width'=>'150','height'=>'150','class'=>'img-circle']);
    }else{
        echo Html::img('@web/uploads/konten/l.png',['width'=>'150','height'=>'150','class'=>'img-circle']);
    }
    ?>
<br /><br />
<?= Html::a('Profil Saya', Url::toRoute(['users/view', 'id' => Yii::$app->user->identity->id]),['class'=>'btn btn-primary']) ?>
</center>      

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;


$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
   <div class="container">  
     <div class="row">
        <div class="col-md-12">
        <center>
            <?php echo Html::img('@web/uploads/konten/coconut.png',['width'=>'150','height'=>'190']) ?>
        </center>
        </div>
    </div>
    <div class="row">
        <div class="col-md-1">
            <span class="fa fa-5x fa-rocket text-warning"></span>
        </div>
        <div class="col-md-6">
            <h1><b>Tujuan <small>COCONUT</small></b></h1>
            <p>
                <b>COCONUT</b> bertujuan membentuk mahasiswa yang kreatif untuk mewujudkan Tri
    Dharma Perguruan Tinggi dan Sumpah Mahasiswa yang mengarah pada 
    pengembangan kreativitas mahasiswa dalam bidang penalaran dan keilmuan yang
    berkaitan dengan spesialisasi  IT.
            </p>
        </div>
        
    </div>
    <div class="row">
        <div class="col-md-1 col-md-offset-5">
            <span class="fa fa-5x fa-cogs text-info"></span>
        </div>
        <div class="col-md-6 ">
            <h1><b>Usaha <small>COCONUT</small></b></h1>
            <p>
            <ul>
               <li>
                Mengarahkan Mahasiswa untuk  berperan aktif dalam mewujudkan cita – cita 
                dan tujuan nasional  melalui Tri Dharma perguruan tinggi dan Sumpah
                Mahasiswa. 
               </li>
               <li>
                Membina dan mengembangkan kualitas serta meningkatkan kesejahteraan
                anggota 
               </li>
               <li>
                Usaha-usaha lain secara nyata dan bertanggung jawab yang menunjang tujuan
                organisasi.
               </li>
            </ul>
            </p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-1">
            <span class="fa fa-5x fa-users text-success"></span>
        </div>
        <div class="col-md-6">
            <h1><b>Status <small>COCONUT</small></b></h1>
            <p>
                <b>COCONUT</b> adalah organisasi kemahasiswaan yang berbentuk media pembelajaran
                sosial dan sains yang bersifat otonom 
            </p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6 col-md-offset-6">

        </div>
    </div>

<hr class="alert-info">
   </div>
</div>

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
  <div class="container"> 
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textArea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(),[
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
   </div>     
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">
  <div class="container"> 
    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>
  </div>
</div>

views/site/index.php
<?php

/* @var $this yii\web\View */
use yii\helpers\Html;

$this->title = 'Daftar | coconut.or.id';
?>

<div class="site-index">
    <div class="affix" style="top: 55px; z-index:-1;">
        <?= Html::img('@web/uploads/konten/home.jpg',['class'=>'img-responsive']) ?>
    </div>   
  <div class="container"> 
          <div class="row">
              <div class="col-md-8">
                    <center>
                        <?php //echo Html::img('@web/uploads/konten/coconutlogo.png',['class'=>'img-responsive']) ?>
                    </center>
                </div>
                <div class="col-md-4">    
                    <?php
                        if (Yii::$app->user->isGuest){
                            echo "<div class='alert'>";
                            echo $this->render('_form',['model' => $model,]);
                            echo "</div>";
                        } else{
                            echo $this->render('_halo');

                        }
                     ?>
                   
                </div>
            </div> 
      </div> 
         
  </div>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <div class="container">   
        <div class="row">
            <div class="col-lg-7">

            </div>
            <div class="col-lg-4">
                <blockquote>
                 <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'options' => ['class' => 'form-horizontal'],
        'fieldConfig' => [
            'template' => "<div class=\"col-lg-12\">{input}{error}</div>\n",
           
        ],
    ]); ?>

        <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"col-lg-12\">{input} {label}{error}</div>\n",
        ]) ?>
       
            <?= Html::submitButton('Masuk', ['class' => 'btn btn-primary btn-lg', 'name' => 'login-button']) ?>
            
      

    <?php ActiveForm::end(); ?>
                </blockquote>
            </div>
        </div>
   
  </div>  
</div>

views/site/verivikasiakun.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\captcha\Captcha;
use yii\helpers\Url;

$this->title = 'Verivikasi Akun';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-verivikasiakun">
    <div class="container">   
        <center> 
            <?php if (Yii::$app->session->hasFlash('kodesend')): ?>
        <div class="alert alert-success">
            Kode Verivikasi anda telah dikirim ke email anda.
        </div>
            <?php endif; ?>
                 <h1><?= Html::encode($this->title) ?></h1>
                 <p>Silahkan Memasukkan Kode Verivikasi yang telah dikirim di email kamu dan ketik kode captcha
                 <br />Jika Belum Menerima Kode Verivikasi klik <?= Html::a('Kirim Ulang Kode Verivikasi', Url::toRoute(['site/kirimkode'])) ?>
                 </p>
                 
    <?php $form = ActiveForm::begin([
        'id' => 'verivikasiakun-form',
        'options' => ['class' => 'form-horizontal'],
        'fieldConfig' => [
            'template' => "<div class=\"col-md-2 col-md-offset-5\">{input}{error}</div>\n",
           
        ],
    ]); ?>

        <?= $form->field($model, 'kodeverivikasi')->textInput(['autofocus' => true]) ?>
                 
        <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
           'template' => '{image}{input}',
       ]) ?>
        <?= Html::submitButton('Verivikasi Akun Saya', ['class' => 'btn btn-primary btn-lg', 'name' => 'login-button']) ?>
            
      

    <?php ActiveForm::end(); ?>
        </center> 
            </div>
        </div>
 