models/User.php
<?php

namespace app\models;

class User extends \yii\base\Object implements \yii\web\IdentityInterface
{
    public $id;
    public $username;
    public $password;
    public $authKey;
    public $accessToken;

    private static $users = [
        '100' => [
            'id' => '100',
            'username' => 'admin',
            'password' => 'admin',
            'authKey' => 'test100key',
            'accessToken' => '100-token',
        ],
        '101' => [
            'id' => '101',
            'username' => 'demo',
            'password' => 'demo',
            'authKey' => 'test101key',
            'accessToken' => '101-token',
        ],
    ];


    /**
     * @inheritdoc
     */
    public static function findIdentity($id)
    {
        return isset(self::$users[$id]) ? new static(self::$users[$id]) : null;
    }

    /**
     * @inheritdoc
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        foreach (self::$users as $user) {
            if ($user['accessToken'] === $token) {
                return new static($user);
            }
        }

        return null;
    }

    /**
     * Finds user by username
     *
     * @param string $username
     * @return static|null
     */
    public static function findByUsername($username)
    {
        foreach (self::$users as $user) {
            if (strcasecmp($user['username'], $username) === 0) {
                return new static($user);
            }
        }

        return null;
    }

    /**
     * @inheritdoc
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @inheritdoc
     */
    public function getAuthKey()
    {
        return $this->authKey;
    }

    /**
     * @inheritdoc
     */
    public function validateAuthKey($authKey)
    {
        return $this->authKey === $authKey;
    }

    /**
     * Validates password
     *
     * @param string $password password to validate
     * @return boolean if password provided is valid for current user
     */
    public function validatePassword($password)
    {
        return $this->password === $password;
    }
}

models/Users.php
<?php

namespace app\models;

use Yii;
use yii\base\Model;
use yii\base\NotSupportedException;
use yii\db\ActiveRecord;
use yii\helpers\Security;
use yii\web\IdentityInterface;

/**
 * This is the model class for table "users".
 *
 * @property string $id
 * @property string $a_nama
 * @property string $a_alamat
 * @property string $a_email
 * @property string $a_password
 * @property string $a_no_tlp
 * @property string $a_kota_lahir
 * @property string $a_tgl_bln_thn_lahir
 * @property string $a_jkelamin
 * @property string $a_thnlulus
 * @property string $a_asalsekolah
 * @property string $a_alasanmasuk
 * @property integer $a_angkatan
 * @property string $a_nra
 * @property string $a_jabatan
 * @property string $a_spesialisasi
 * @property string $a_foto
 * @property string $a_kode
 * @property integer $level_id
 */
class Users extends \yii\db\ActiveRecord implements IdentityInterface
{
    /**
     * @inheritdoc
     */
    public $verifyCode;
    public $file;
    public $kodeverivikasi;
    public static function tableName()
    {
        return 'users';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['a_nama', 'a_email', 'a_password', 'a_no_tlp', 'a_kode', 'level_id'], 'required'],
            [['a_alamat', 'a_jkelamin', 'a_alasanmasuk', 'a_jabatan', 'a_spesialisasi'], 'string'],
            [['a_tgl_bln_thn_lahir'], 'safe'],
            [['a_angkatan', 'level_id'], 'integer'],
            [['file'],'file'],
            [['a_nama', 'a_email', 'a_foto'], 'string', 'max' => 100],
            [['a_password','kodeverivikasi', 'a_kode',], 'string', 'max' => 255],
            [['a_no_tlp'], 'string', 'max' => 17],
            [['a_kota_lahir'], 'string', 'max' => 50],
            [['a_thnlulus'], 'string', 'max' => 4],
            [['a_asalsekolah'], 'string', 'max' => 250],
            [['a_nra'], 'string', 'max' => 11],
            ['verifyCode', 'captcha'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'a_nama' => 'Nama Lengkap',
            'a_alamat' => 'Alamat Rumah',
            'a_email' => 'Email',
            'a_password' => 'Password',
            'a_no_tlp' => 'No Telepon / Hp',
            'a_kota_lahir' => 'Kota Lahir',
            'a_tgl_bln_thn_lahir' => 'Tanggal Lahir',
            'a_jkelamin' => 'Jenis Kelamin',
            'a_thnlulus' => 'Tahun Lulus',
            'a_asalsekolah' => 'Nama Asal Sekolah',
            'a_alasanmasuk' => 'Alasan Masuk COCONUT',
            'a_angkatan' => 'Angkatan',
            'a_nra' => 'NRA',
            'a_jabatan' => 'Jabatan Saat Menjabat BPH',
            'a_spesialisasi' => 'Keahlian Yang Di Kuasai',
            'a_foto' => 'Foto',
            'a_kode' => 'Kode',
            'level_id' => 'Level ID',
            'verifyCode' => 'Verification Code',
            'file' => 'Foto',
        ];
    }
    
    //generate password md5
        public function validatePassword($password) 
        { 
                return $this->hashPassword($password,$this->a_kode)===$this->a_password; 
        } 
     
        public function hashPassword($password,$salt) 
        { 
                return md5($salt.$password); 
        } 
 
	 public function generateSalt() 
        { 
                return uniqid('',true); 
	}
        
            /** INCLUDE USER LOGIN VALIDATION FUNCTIONS**/
        /**
     * @inheritdoc
     */
    public static function findIdentity($id)
    {
        return static::findOne($id);
    }

    /**
     * @inheritdoc
     */
/* modified */
    public static function findIdentityByAccessToken($token, $type = null)
    {
          return static::findOne(['access_token' => $token]);
    }
 
/* removed
    public static function findIdentityByAccessToken($token)
    {
        throw new NotSupportedException('"findIdentityByAccessToken" is not implemented.');
    }
*/
    /**
     * Finds user by username
     *
     * @param  string    
     * @return static|null
     */
    public static function findByEmail($email)
    {
        return static::findOne(['a_email' => $email]);
    }

    /**
     * Finds user by password reset token
     *
     * @param  string      $token password reset token
     * @return static|null
     */
    public static function findByPasswordResetToken($token)
    {
        $expire = \Yii::$app->params['user.passwordResetTokenExpire'];
        $parts = explode('_', $token);
        $timestamp = (int) end($parts);
        if ($timestamp + $expire < time()) {
            // token expired
            return null;
        }

        return static::findOne([
            'password_reset_token' => $token
        ]);
    }

    /**
     * @inheritdoc
     */
    public function getId()
    {
        return $this->getPrimaryKey();
    }

    /**
     * @inheritdoc
     */
    public function getAuthKey()
    {
        return $this->auth_key;
    }

    /**
     * @inheritdoc
     */
    public function validateAuthKey($authKey)
    {
        return $this->getAuthKey() === $authKey;
    }

    /**
     * Generates password hash from password and sets it to the model
     *
     * @param string $password
     */
    public function setPassword($password)
    {
        $this->password_hash = Security::generatePasswordHash($password);
    }

    /**
     * Generates "remember me" authentication key
     */
    public function generateAuthKey()
    {
        $this->auth_key = Security::generateRandomKey();
    }

    /**
     * Generates new password reset token
     */
    public function generatePasswordResetToken()
    {
        $this->password_reset_token = Security::generateRandomKey() . '_' . time();
    }

    /**
     * Removes password reset token
     */
    public function removePasswordResetToken()
    {
        $this->password_reset_token = null;
    }
    /** EXTENSION MOVIE **/

}

controllers/UsersController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Users;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\web\UploadedFile;
use kartik\mpdf\Pdf;

/**
 * UsersController implements the CRUD actions for Users model.
 */
class UsersController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['index','view','update','create','delete'],
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['index'],
                        'roles' => ['?'],
                    ],
                    [
                        'allow' => true,
                        'actions' => ['index','view','update'],
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Users models.
     * @return mixed
     */
    public function actionIndex()
    {
        // mengambil data angkatan
        $jumlah_angkatan = Users::findBySql('SELECT DISTINCT a_angkatan from users where level_id = 3 ORDER BY a_angkatan ASC')->all();
        foreach ($jumlah_angkatan as $a){
        $dataProvider[] = new ActiveDataProvider([
            'query' => Users::findBySql('SELECT * from users WHERE a_angkatan = '.$a->a_angkatan.' ORDER BY a_nama ASC'),
        ]);
    }
        
        
        return $this->render('index', [
            'dataProvider' => $dataProvider,'angka'=>$jumlah_angkatan,
        ]);
    }

    /**
     * Displays a single Users model.
     * @param string $id
     * @return mixed
     */
    public function actionView($id)
    {
        $model = $this->findModel($id);
        
        if(Yii::$app->user->identity->id == $id){
            if(Yii::$app->user->identity->level_id<=4){
            return $this->render('profil', [
              'model' => $model,
            ]);}
            else{
               return $this->redirect(['site/verivikasiakun']); 
            }
        }else{
            return $this->render('view', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Creates a new Users model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Users();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Users model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $pas = $model->a_password;
        
        if ($model->load(Yii::$app->request->post())) {
         
            //cek penggantian password
         if($pas != $model->a_password){
            $model->a_kode=$model->generateSalt(); 
            $model->a_password=$model->hashPassword($model->a_password,$model->a_kode);
         }   
         
           //cek penggantian foto
         if(strlen(trim(UploadedFile::getInstance($model,'file')))>0){
             $model->file = UploadedFile::getInstance($model,'file');
             $foto = $model->a_foto;
             $model->a_foto = $model->id.'.'.$model->file->extension;
             $fg = 2;
         }else{
             $fg = -1;
             
         }
         
         if($model->save()){   
             //upload foto
             if($fg > 0){ 
                @unlink('uploads/users/'.$foto);
                $model->file->saveAS('uploads/users/'.$model->a_foto); 
             }
             
            return $this->redirect(['view', 'id' => $model->id]);
            }           
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Users model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Users model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return Users the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Users::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
    
    public function actionReport() {
    // get your HTML raw content without any layouts or scripts
    $model = $this->findModel(Yii::$app->user->identity->id);
    $content = $this->renderPartial('tiket',['model'=>$model]);
 
    // setup kartik\mpdf\Pdf component
    $pdf = new Pdf([
        // set to use core fonts only
        'mode' => Pdf::MODE_UTF8, 
        // A4 paper format
        'format' => Pdf::FORMAT_A4, 
        // portrait orientation
        'orientation' => Pdf::ORIENT_PORTRAIT, 
        // stream to browser inline
        'destination' => Pdf::DEST_BROWSER, 
        // your html content input
        'content' => $content,  
        // format content from your own css file if needed or use the
        // enhanced bootstrap css built by Krajee for mPDF formatting 
        //'cssFile' => '@vendor/kartik-v/yii2-mpdf/assets/kv-mpdf-bootstrap.min.css',
         'cssFile' => '@vendor/bower/bootstrap/dist/css/bootstrap.min.css',
        // any css to be embedded if required
        'cssInline' => '.kv-heading-1{font-size:18px}', 
         // set mPDF properties on the fly
        'options' => ['title' => 'Workshop | COCONUT'],
         // call mPDF methods on the fly
     //   'methods' => [ 
     //       'SetHeader'=>['Workshop | COCONUT'], 
     //       'SetFooter'=>['{PAGENO}'],
     //   ]
        
    ]);
 
    // return the pdf output as per the destination setting
    return $pdf->render(); 
}
}

views/users/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

use yii\captcha\Captcha;
/* @var $this yii\web\View */
/* @var $model app\models\Users */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="users-form">

    <?php $form = ActiveForm::begin(['options'=>['enctype'=>'multipart/form-data']]); ?>

    <h2>Profil Umum</h2>
    
    <?= $form->field($model, 'a_nama')->textInput(['maxlength' => true,'disabled'=>true]) ?>

    <?= $form->field($model, 'a_alamat')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'a_email')->textInput(['maxlength' => true,'disabled'=>true]) ?>

    <?= $form->field($model, 'a_password')->passwordInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'a_no_tlp')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'a_kota_lahir')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'a_tgl_bln_thn_lahir')->textInput() ?>

    <?= $form->field($model, 'a_jkelamin')->dropDownList([ 'laki-laki' => 'Laki-laki', 'perempuan' => 'Perempuan', ], ['prompt' => '']) ?>
    <h2>Profil Pendidikan</h2>
    <?= $form->field($model, 'a_thnlulus')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'a_asalsekolah')->textInput(['maxlength' => true]) ?>
    <h2>Profil Keanggotaan</h2>
    <?= $form->field($model, 'a_alasanmasuk')->textarea(['rows' => 6]) ?>
    
    <?php if($model->level_id <= 3){?>
    
    <?= $form->field($model, 'a_angkatan')->textInput() ?>

    <?= $form->field($model, 'a_nra')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'a_jabatan')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'a_spesialisasi')->textarea(['rows' => 6]) ?>
    
    <?php } ?>

    <?= $form->field($model, 'file')->fileInput() ?>

     <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
        'template' => '{image}{input}',
    ]) ?>
    
    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/users/_view.php
<?php
use yii\helpers\Html;
use yii\helpers\HtmlPurifier;
use yii\helpers\Url;
?>
<div class="post col-md-3">
    <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title"><?= Html::encode($model->a_nama) ?></h3>
        </div>
        <div class="panel-body">
            <?php if($model->a_foto!=null){
                echo Html::img('@web/uploads/users/'.$model->a_foto,['width'=>'150','height'=>'150','class'=>'img-circle']);
            }else{
                echo Html::img('@web/uploads/konten/l.png',['width'=>'150','height'=>'150','class'=>'img-circle']);
            } ?>
            <?= Html::a('Profil', Url::toRoute(['users/view', 'id' => $model->id]),['class'=>'btn btn-success','title' => $model->a_nama]) ?>
        </div>
    </div>    
</div>

views/users/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Users */

$this->title = 'Create Users';
$this->params['breadcrumbs'][] = ['label' => 'Users', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="users-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/users/index.php
<?php

use yii\helpers\Html;
use yii\widgets\ListView;
use yii\widgets\Pjax;
/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Users';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="users-index">
    <div class="container">
  <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <?php 
        echo "<li role='presentation' class='active'><a href='#' aria-controls='home' role='tab' data-toggle='tab'><span class='glyphicon glyphicon-user'></span></a></li>";      
          
        foreach ($angka as $aa){
            if ($aa->a_angkatan == 0){
          echo "<li role='presentation'><a href='#angkatan$aa->a_angkatan' aria-controls='angkatan$aa->a_angkatan' role='tab' data-toggle='tab'>Badan Pendiri</a></li>";      
            }else{
          echo "<li role='presentation'><a href='#angkatan$aa->a_angkatan' aria-controls='angkatan$aa->a_angkatan' role='tab' data-toggle='tab'>Agk $aa->a_angkatan</a></li>";  
            }
        }
    ?>
  </ul>
  <div class="tab-content">
        <?php 
            foreach ($angka as $a){
             echo "<div role='tabpanel' class='tab-pane active' id='angkatan$a->a_angkatan'>";
              if ($a->a_angkatan == 0){
                       echo "<h2> Badan Pendiri</h2>";
                 }else{
                       echo "<h2> Angkatan ".$a->a_angkatan."</h2>";
                  }
            
             echo "<div class='row'>";
             echo  ListView::widget([
                'dataProvider' => $dataProvider[$a->a_angkatan],
                'itemView' => '_view',
                'layout'=>'{items}'

            ]); 
             echo "</div></div>"; 
            }
        ?>
  </div>

</div>
      
    

views/users/profil.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\helpers\Url;
/* @var $this yii\web\View */
/* @var $model app\models\Users */

$this->title = $model->a_nama;
$this->params['breadcrumbs'][] = ['label' => 'Users', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="users-view">
  <div class="container">  
      <div class="row">
        <div class="col-lg-3">
            <center> 
                <?= Html::img('@web/uploads/users/'.$model->a_foto,['class'=>'img-responsive img-thumbnail']) ?>
            </center>  <br />    
                <?= Html::a('Update Profil', Url::toRoute(['users/update', 'id' => $model->id]),['class'=>'btn btn-warning btn-block']); ?>
            <?php if(Yii::$app->user->identity->level_id==4){
                echo "<p class='text-danger'>*) Sebelum Mencetak Formulir Harap Melengkapi Semua Data Profil Kamu</p>";
                echo Html::a('Cetak Formulir', Url::toRoute(['users/formulir', 'id' => $model->id]),['class'=>'btn btn-danger btn-block']);
                echo Html::a('Tiket Seminar', Url::toRoute(['users/report']),['class'=>'btn btn-info btn-block']);
                
             }
            ?>
            
            
        </div>
        <div class="col-lg-8">
            <h2>Profil Umum</h2>
          <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'a_nama',
            'a_alamat:ntext',
            'a_email:email',
            'a_no_tlp',
            'a_kota_lahir',
            'a_tgl_bln_thn_lahir',
            'a_jkelamin',
        ],
    ]) ?>  
             <h2>Profil Pendidikan</h2>
             <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'a_thnlulus',
            'a_asalsekolah',
        ],
    ]) ?>  
             <?php if($model->level_id <= 3){?>
              <h2>Profil Keanggotaan</h2>
             <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'a_alasanmasuk:ntext',
            'a_angkatan',
            'a_nra',
            'a_jabatan:ntext',
            'a_spesialisasi:ntext',
        ],
             ]) ?> <?php }else{ ?>
<?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'a_alasanmasuk:ntext',
         ],   
             ]) ?> <?php } ?>
        </div>
    </div>
  </div>
</div>

views/users/tiket.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\helpers\Url;
/* @var $this yii\web\View */
/* @var $model app\models\Users */

?>
<div class="users-view">
     
  <div class="container"> 
      
      <h3 class="text-info alert alert-danger">WORKSHOP | COCONUT</h3>
      <table width="100%">
          <tr>
              <td width="65%">
                  <span style="font-size: 30px;">Membangun</span> 
                  <span class="alert-success" style="font-size: 50px">Aplikasi</span> <br />
                  <span class="alert-info" style="font-size: 40px">Database</span>
                  <span style="font-size: 20px"> Menggunakan </span>
                  <span class="alert-warning" style="font-size: 50px">PHP</span>
              </td>
              <td>
                  <table>
                      <tr class="bg-info">
                         <td valign="top">
                                No  
                          </td>
                          <td valign="top">
                                : 
                          </td>
                          <td valign="top">
                              <b>    <?= ' ON'.$model->id ?> </b>
                          </td>
                      </tr>  
                       <tr>
                        <td valign="top">
                              Tempat
                        </td>
                        <td valign="top">
                              : 
                        </td>
                        <td valign="top">
                            <b>  Meeting Room <br /> STMIK PROFESIONAL MAKASSAR </b>
                        </td>
                    </tr>
                    <tr class="bg-info">
                        <td valign="top">
                              Tgl/waktu
                        </td>
                        <td valign="top">
                              : 
                        </td>
                        <td valign="top">
                            <b>  18 Juni 2016,<br /> 10.00 - Selesai </b>
                        </td>
                    </tr>
                             </table>            
              
              </td>
             
         
      </table>    
      <h5 class="alert alert-success">Contact Person : Tri Nirwana - 0852 9988 7070 / Faisal : 0896 9728 6052 </h5>
       
                

  </div>
</div>

views/users/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Users */

$this->title = 'Update Users: ' . $model->a_nama;
$this->params['breadcrumbs'][] = ['label' => 'Users', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="users-update">
    <div class="container">
         <div class="row">
            <div class="col-lg-3">
                <center> 
                    <?= Html::img('@web/uploads/users/'.$model->a_foto,['class'=>'img-responsive img-thumbnail']) ?>
                </center> 
            </div>
            <div class="col-lg-8">
                <?= $this->render('_form', [
                    'model' => $model,
                ]) ?>
            </div>
         </div>
    </div>
</div>

views/users/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\helpers\Url;
/* @var $this yii\web\View */
/* @var $model app\models\Users */

$this->title = $model->a_nama;
$this->params['breadcrumbs'][] = ['label' => 'Users', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="users-view">
  <div class="container">  
      <div class="row">
        <div class="col-lg-3">
            <center> 
                <?= Html::img('@web/uploads/users/'.$model->a_foto,['class'=>'img-responsive img-thumbnail']) ?>
            </center>      
        </div>
        <div class="col-lg-8">
            <?php if(Yii::$app->user->identity->level_id==3){?>
            <h2>Profil Umum</h2>
          <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'a_nama',
            'a_alamat:ntext',
            'a_email:email',
            'a_no_tlp',
            'a_kota_lahir',
            'a_tgl_bln_thn_lahir',
            'a_jkelamin',
        ],
    ]) ?>  
             <h2>Profil Pendidikan</h2>
             <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'a_thnlulus',
            'a_asalsekolah',
        ],
    ]) ?>  
              <h2>Profil Keanggotaan</h2>
             <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'a_alasanmasuk:ntext',
            'a_angkatan',
            'a_nra',
            'a_jabatan:ntext',
            'a_spesialisasi:ntext',
        ],
    ]) ?>
            <?php }else{ ?>
            
              <div class="alert alert-info">
                  <h2 class="text-danger">Profil <small> <?= $model->a_nama ?> </small></h2>
                  <p class="text-danger">
                      Maaf anda belum diperbolehkan melihat profil lengkap saudara/i <?= $model->a_nama ?>
                  </p><br />
                  <?= Html::a('Kembali', Url::toRoute(['users/index']),['class'=>'btn btn-lg btn-danger']) ?>
              </div>
              
            <?php } ?>
        </div>
    </div>
  </div>
</div>